name: Flask CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
      - name: GitLeaks Secret Scan
        uses: zricethezav/gitleaks-action@v2
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
  deploy:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3 
      - name: Set up kubeconfig file
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
      - name: Deploy with kubectl
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
